name: aya_Test
on: [push,pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.*"
      - name: Instal Dependencies
        run: npm install
      - name: Run Tests
        run: npm run test
