name: Running Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set Up Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.*"  # Using Node.js 20 version
        
      - name: Install Dependencies
        run: npm install
        
      - name: Run Tests
        run: npm run test  # Ensure "test" script is defined in your package.json
